### ISSUE TITLE
[Feature Request] Integrate "title" from the anime-offline-database

### ISSUE THREAD

**Issue by Goldenfreddy0703** [Fribb/anime-lists#19] opened 2024-05-28 06:31 UTC
Hey there, sorry to bother you but would it be possible to integrate the "title" from the anime-offline-database? Huge reason why is cause i have noticed a few animes titles from the anime-offline-database that are the exact same as well as the type so what i did was i created a database script to help me merge the data and all. 

Here are a few examples of what i noticed:

anime-list-full.json
```
  {
    "anime-planet_id": "aikatsu",
    "kitsu_id": 7205,
    "type": "TV",
    "notify.moe_id": "qTBdtFmig",
    "anilist_id": 15061
  },
```

```
  {
    "livechart_id": 923,
    "thetvdb_id": 263310,
    "anisearch_id": 7982,
    "anidb_id": 9348,
    "mal_id": 15061,
    "type": "TV"
  },
```
These could be merged for example. 

anime-offline-database.json
```
    {
      "sources": [
        "https://anilist.co/anime/15061",
        "https://anime-planet.com/anime/aikatsu",
        "https://kitsu.io/anime/7205",
        "https://notify.moe/anime/qTBdtFmig"
      ],
      "title": "Aikatsu!",
      "type": "TV",
      "episodes": 50,
      "status": "FINISHED",
      "animeSeason": {
        "season": "FALL",
        "year": 2012
      },
      "picture": "https://cdn.anime-planet.com/anime/primary/aikatsu-1.jpg?t=1625896440",
      "thumbnail": "https://cdn.anime-planet.com/anime/primary/aikatsu-1-190x269.jpg?t=1625896440",
      "synonyms": [
        "Aidoru ga Tsudou!",
        "Aikatsu! Idol Katsudou! Idol ga Tsudou!",
        "Idol ga Tsudou!",
        "アイカツ!",
        "アイカツ！",
        "アイカツ！アイドルカツドウ！",
        "アイドルカツドウ！"
      ],
      "relatedAnime": [
        "https://anilist.co/anime/101043",
        "https://anilist.co/anime/111082",
        "https://anilist.co/anime/128872",
        "https://anilist.co/anime/20181",
        "https://anilist.co/anime/21648",
        "https://anime-planet.com/anime/aikatsu-2",
        "https://anime-planet.com/anime/aikatsu-3",
        "https://anime-planet.com/anime/aikatsu-4",
        "https://anime-planet.com/anime/aikatsu-dai-starmiya-ichigo-matsuri-zenyasai",
        "https://anime-planet.com/anime/aikatsu-friends",
        "https://anime-planet.com/anime/aikatsu-music-award-minna-de-shou-wo-moracchaima-show",
        "https://anime-planet.com/anime/aikatsu-nerawareta-mahou-no-aikatsu-card",
        "https://anime-planet.com/anime/aikatsu-on-parade",
        "https://anime-planet.com/anime/aikatsu-planet",
        "https://anime-planet.com/anime/aikatsu-stars",
        "https://anime-planet.com/anime/aikatsu-stars-the-movie",
        "https://anime-planet.com/anime/aikatsu-the-movie",
        "https://kitsu.io/anime/10093",
        "https://kitsu.io/anime/10942",
        "https://kitsu.io/anime/11868",
        "https://kitsu.io/anime/12256",
        "https://kitsu.io/anime/41015",
        "https://kitsu.io/anime/42497",
        "https://kitsu.io/anime/7972",
        "https://kitsu.io/anime/8499",
        "https://notify.moe/anime/68ZwHbFVR",
        "https://notify.moe/anime/6weqpFmmR",
        "https://notify.moe/anime/CAU_tFiig",
        "https://notify.moe/anime/D4QJW7jZg",
        "https://notify.moe/anime/YDQr2zfGR",
        "https://notify.moe/anime/anSstFimR",
        "https://notify.moe/anime/vCx0tKiiR",
        "https://notify.moe/anime/x6YR2Fmmg"
      ],
      "tags": [
        "acting",
        "based on a card game",
        "boarding school",
        "card battle",
        "cgi",
        "cute girls doing cute things",
        "dancing",
        "ensemble cast",
        "episodic",
        "fashion",
        "female protagonist",
        "fitness",
        "henshin",
        "idol",
        "idols",
        "japan",
        "kids",
        "music",
        "music school",
        "outdoor",
        "primarily female cast",
        "primarily teen cast",
        "school",
        "school life",
        "shoujo",
        "showbiz",
        "slice of life",
        "the arts",
        "work"
      ]
    },
```

```
    {
      "sources": [
        "https://anidb.net/anime/9348",
        "https://anisearch.com/anime/7982",
        "https://livechart.me/anime/923",
        "https://myanimelist.net/anime/15061"
      ],
      "title": "Aikatsu!",
      "type": "TV",
      "episodes": 178,
      "status": "FINISHED",
      "animeSeason": {
        "season": "FALL",
        "year": 2012
      },
      "picture": "https://cdn.myanimelist.net/images/anime/6/74783.jpg",
      "thumbnail": "https://cdn.myanimelist.net/images/anime/6/74783t.jpg",
      "synonyms": [
        "Aidoru ga Tsudou!",
        "Aikatsu! 2",
        "Aikatsu! Idol Activities!",
        "Aikatsu! Idol Katsudou!",
        "Aikatsu! Idol Katsudou! Idol ga Tsudou!",
        "Aikatsu! Idol Katsudō!",
        "Idol ga Tsudou!",
        "Idol ga Tsudou! 2",
        "アイカツ!",
        "アイカツ! アイドルカツドウ!",
        "アイカツ！ アイドルカツドウ！",
        "アイカツ！アイドルカツドウ！",
        "偶像活动"
      ],
      "relatedAnime": [
        "https://anidb.net/anime/10482",
        "https://anidb.net/anime/11262",
        "https://anidb.net/anime/11526",
        "https://anidb.net/anime/11934",
        "https://anidb.net/anime/12821",
        "https://anidb.net/anime/13755",
        "https://anidb.net/anime/14631",
        "https://anidb.net/anime/15047",
        "https://anidb.net/anime/15479",
        "https://anidb.net/anime/17699",
        "https://anisearch.com/anime/10040",
        "https://anisearch.com/anime/10474",
        "https://anisearch.com/anime/11149",
        "https://anisearch.com/anime/12220",
        "https://anisearch.com/anime/13284",
        "https://anisearch.com/anime/14565",
        "https://anisearch.com/anime/17482",
        "https://anisearch.com/anime/9493",
        "https://livechart.me/anime/10112",
        "https://livechart.me/anime/11182",
        "https://livechart.me/anime/11288",
        "https://livechart.me/anime/11334",
        "https://livechart.me/anime/1616",
        "https://livechart.me/anime/1785",
        "https://livechart.me/anime/2037",
        "https://livechart.me/anime/2046",
        "https://livechart.me/anime/3059",
        "https://livechart.me/anime/450",
        "https://livechart.me/anime/9565",
        "https://livechart.me/anime/9824",
        "https://myanimelist.net/anime/22819",
        "https://myanimelist.net/anime/28723",
        "https://myanimelist.net/anime/30845",
        "https://myanimelist.net/anime/32717",
        "https://myanimelist.net/anime/32806",
        "https://myanimelist.net/anime/37204",
        "https://myanimelist.net/anime/40266",
        "https://myanimelist.net/anime/42653",
        "https://myanimelist.net/anime/52993"
      ],
      "tags": [
        "ganbatte",
        "idol",
        "idols (female)",
        "music",
        "new",
        "present",
        "school",
        "school life",
        "shoujo",
        "slice of life",
        "the arts"
      ]
    },
```
Same Anime from Offline Database can be merged as well. 

Sometimes its hard to map ids with multiple animes but it would really help if you could Integrate titles from the anime-offline-database. If not then don't worry about it, i could probably try match and compare but would take alot of work.
 
Thank you

**Comment by Fribb** [comment] 2024-05-28 07:25
Thanks for this request but I have to close this as not planned. This isn't the right place for fixing things like this.

Let me explain why. This project exists to provide a condensed form of the mappings between websites that have anime so that when you have an ID from any of these websites, you can get the ID of the other websites easily.

Adding a title wouldn't really serve that purpose and just bloat the site unnecessarily.

It would also open up the project for further feature requests to add more titles or names to the list bloating it even more. For example, if I just use the title of the anime-offline-database, someone could request that the list now also include all synonyms too.

This would go against the "purity of purpose" of this project.

Since this project is only the condensed form of those related projects, I also want to prevent unnecessary "content management" here. So any incorrect mappings should be fixed on the source instead of manually edited here. This was already the case in the first iterations of the project in which I needed to invest a lot of time to validate the mappings which just wasn't something I was willing to spend time on, especially if other projects already invested that time.

What I want to say with this is that when you think there is a duplicate and even mention the anime-offline-database, then that would also be the place where you should request that change or get it fixed.

Just to reiterate this, this project is only running through the anime-offline-database and stripping everything except the IDs from it. So if anything is incorrect, fixing it on this side would not address the actual issue which would be the duplicate on the anime-offline-database.

And when the issue is addressed on the anime-offline-database side this would then correct itself on this side too the next time the lists are updated.

**Closed by Fribb** 2024-05-28 07:25 UTC
