### ISSUE TITLE
Merge request

### ISSUE THREAD

**Issue by hekkr000** [Fribb/anime-lists#17] opened 2022-06-06 14:32 UTC
Hi! I was working on something similar for the past few weeks, and your list was a huge help. I would like to share the connections that I made using some magic lookups and computer vision. I checked all the records myself manually, but please make sure that they are up to the standard! JSON attached.

My priority is TMDB and AniList, but since there are usable connections, I also added the MAL ids.

Have a nice day, and thank you for your work!
[diff.txt](https://github.com/Fribb/anime-lists/files/8845134/diff.txt)

**Comment by Fribb** [comment] 2022-06-06 15:40
Thanks for that but I will close this without merging it.

This is nothing against you or the work you put into it but rather that these lists are automatically generated based on existing information. I have no plan to start doing manual edits or modifications, I already tried that when I started this project and it was a pain to maintain.

To be clear it is not that I don't want to get this fixed, this is just the wrong place to do it because it doesn't address the root cause of this problem.

The way the list is generated is that I condense the information and, in the end, look up the individual IDs of TVDB and TMDB on TheMovieDB and their API.

TheMovieDB provides the ability for someone to add different external sources like IMDB, TVDB, FreeBase and TVRage. Those IDs can then be requested through the API like [this](https://developers.themoviedb.org/3/movies/get-movie-external-ids). This allows me to search for any of those IDs on TheMovieDB and get the mapped TMDB ID with very little effort.

If that information doesn't return something then it is just not available on TheMovieDB. That would be a much better place to do those edits and create that mapping.

That way, the next time the list is generated, the mapping is also available here but TheMovieDB also benefits from that information.

**Closed by Fribb** 2022-06-06 15:40 UTC

**Comment by hekkr000** [comment] 2022-06-06 17:34
Oh, okay. I also use the TMDB API, but I've only ever seen the TVDB and IMDB ids there, not the MAL/AniList ones. I would love to update the source, but I don't really understand how you connect them I'm afraid. Could you elaborate?

**Comment by Fribb** [comment] 2022-06-06 17:51
Themoviedb doesn't provide a way to add myanimelist or anilist IDs. What I meant was that you need to add the TVDB ID to the TMDB entry. 

If that mapping is available then then generator that creates the Anime-List can find it by searching for the TVDB ID on the API

When you are on TMDB then edit something and there should be a category "external sources" there you can add the TVDB or IMDB 

That is the only way to currently map more reliably between myanimelist to anidb to thetvdb to themoviedb

**Comment by Fribb** [comment] 2022-06-06 18:59
Well, you could just check the list for the mal-id you mapped manually and see if it has a tvdb-id and then add that to the tmdb entry.

By the way, if you open a show on the tvdb website the ID should be the in the first row of the table

**Comment by hekkr000** [comment] 2022-06-06 20:34
Alright, I've added a couple of them, but about 90% of them doesn't have a TVDB ID on your list, so this is the best I can do. I've also found some where the TVDB ID no longer exists, and a different one is already added on TMDB.

**Comment by Fribb** [comment] 2022-06-07 09:51
I see. well, if there is no TVDB ID then this is because it isn't mapped correctly in the [Anime-Lists/anime-lists](https://github.com/Anime-Lists/anime-lists/) Project and that would be the place to get that sorted out.

I just did a quick search for such a thing:

```
  {
    "livechart_id": 5959,
    "anime-planet_id": "prism-magical-prism-generations",
    "anisearch_id": 6496,
    "anidb_id": 7945,
    "kitsu_id": 5762,
    "mal_id": 9506,
    "type": "OVA",
    "notify.moe_id": "Bx7GtKiig",
    "anilist_id": 9506
  }
```
There is an AniDB ID available so I can use that to query the Anime-Lists project to find the entry there: 
```
<anime anidbid="7945" tvdbid="OVA" defaulttvdbseason="1">
    <name>Prism Mergical: Prism Generations!</name>
    <supplemental-info replace="true">
      <studio>Asahi Production</studio>
      <fanart>
        <thumb dim="1900x1250" colors="" preview="https://sites.google.com/site/anidblist/pm-499692t.jpg">https://sites.google.com/site/anidblist/pm-499692b.jpg</thumb>
      </fanart>
    </supplemental-info>
  </anime>
```
While the entry exists, that particular mapping is ignored in my case because the TVDB ID is marked as "OVA". According to the description: 

> One-off titles that won't ever be added to theTVDB.com (movies, TV specials, one-shot OVAs) are marked by their AniDb.net type, unless they can be associated to a multi-episode series (in which case they use the corresponding theTVDB.com id or "unknown").

But, when I search for that particular episode I get the Show [Prism Ark](https://thetvdb.com/series/prism-ark) and that particular OVA is listed as [Season 0 Episode 7](https://thetvdb.com/series/prism-ark/episodes/4193912)

That means that the [Anime-Lists/anime-lists](https://github.com/Anime-Lists/anime-lists/) Mapping would have to be adjusted to `anidbid="7945" tvdbid="93491" defaulttvdbseason="0"` for this to work from what I can tell.

**Comment by hekkr000** [comment] 2022-06-07 13:17
Thanks for the detailed explanation, I will look into using this project as well, and see if I can either contribute or counter-reference it to get the proper ids!
